import { Asset } from "../interfaces/Asset";

export const OPERATIONAL_ASSETS = [
  {
    id: "A1",
    unitId: "5050",
    status: "Operational",
  },
  {
    id: "A2",
    unitId: "5052",
    status: "Operational",
  },
  {
    id: "A3",
    unitId: "5059",
    status: "Operational",
  },
  {
    id: "A4",
    unitId: "5060",
    status: "Operational",
  },
  {
    id: "A5",
    unitId: "5071",
    status: "Operational",
  },
];

export const SHOP_VIEW_ASSETS: Array<Asset> = [
  {
    _id: "dummy-id-1",
    unitId: "2001",
    fms: "MiningFMS",
    modelCode: "MODEL-A",
    equipmentType: "H",
    truckType: "Standard",
    status: "down_waiting",
    wencoStatus: null,
    minestarStatus: null,
    location: "Recent Downs",
    refreshedTime: "2025-01-01T00:00:00.000Z",
    operatingType: "Autonomous",
    activeEvent: {
      _id: "dummy-event-1",
      unitId: "2001",
      status: "down_waiting",
      hoursInStatus: "3 hours",
      workOrderNumber: "WO-123",
      purchaseOrderNumber: "PO-123",
      scheduleOutDate: "",
      scheduledInDate: "",
      secondaryStatus: "Inspection",
      location: "Recent Downs",
      bay: "",
      releasedToOps: false,
      lastUpdatedBy: "",
      updatedAt: "2025-01-01T00:00:00.000Z",
      conflict: false,
      purchaseOrderExpectedDate: "",
      isManuallyAdded: false,
      isStatusChangeManual: false,
      downDate: "2025-01-01T00:00:00.000Z",
      revisedOutDate: "",
      toBePlanned: false,
      washed: false,
      washComplete: false,
      toBeTowed: false,
      toBeScheduled: false,
      readyToBreakIn: false,
      assignedTechnicians: [],
      temp_assignedTechnicians: [],
      lastUpdated: "",
      actualOutDate: "",
    },
  },
  {
    _id: "dummy-id-2",
    unitId: "2002",
    fms: "MiningFMS",
    modelCode: "MODEL-B",
    equipmentType: "H",
    truckType: "Heavy Duty",
    status: "down_scheduled",
    wencoStatus: null,
    minestarStatus: null,
    location: "Weld Shop",
    refreshedTime: "2025-01-02T08:00:00.000Z",
    operatingType: "Manual",
    activeEvent: {
      _id: "dummy-event-2",
      unitId: "2002",
      status: "down_scheduled",
      hoursInStatus: "8 hours",
      workOrderNumber: "WO-456",
      purchaseOrderNumber: "PO-456",
      scheduleOutDate: "2025-01-03T08:00:00.000Z",
      scheduledInDate: "",
      secondaryStatus: "Routine Maintenance",
      location: "Weld Shop",
      bay: "Bay 3",
      releasedToOps: false,
      lastUpdatedBy: "",
      updatedAt: "2025-01-02T08:45:00.000Z",
      conflict: false,
      purchaseOrderExpectedDate: "",
      isManuallyAdded: false,
      isStatusChangeManual: true,
      downDate: "2025-01-02T08:00:00.000Z",
      revisedOutDate: "",
      toBePlanned: true,
      washed: true,
      washComplete: false,
      toBeTowed: false,
      toBeScheduled: false,
      readyToBreakIn: false,
      assignedTechnicians: [],
      temp_assignedTechnicians: [],
      lastUpdated: "",
      actualOutDate: "",
    },
  },
  {
    _id: "dummy-id-3",
    unitId: "2003",
    fms: "MiningFMS",
    modelCode: "MODEL-C",
    equipmentType: "H",
    truckType: "Light Duty",
    status: "down_unscheduled",
    wencoStatus: null,
    minestarStatus: null,
    location: "Auxiliary Shop",
    refreshedTime: "2025-01-03T14:00:00.000Z",
    operatingType: "Hybrid",
    activeEvent: {
      _id: "dummy-event-3",
      unitId: "2003",
      status: "down_unscheduled",
      hoursInStatus: "24 hours",
      workOrderNumber: "WO-789",
      purchaseOrderNumber: "PO-789",
      scheduleOutDate: "",
      scheduledInDate: "",
      secondaryStatus: "Critical Repair",
      location: "Auxiliary Shop",
      bay: "Bay 1",
      releasedToOps: false,
      lastUpdatedBy: "",
      updatedAt: "2025-01-03T15:00:00.000Z",
      conflict: true,
      purchaseOrderExpectedDate: "",
      isManuallyAdded: true,
      isStatusChangeManual: false,
      downDate: "2025-01-03T14:00:00.000Z",
      revisedOutDate: "",
      toBePlanned: false,
      washed: false,
      washComplete: false,
      toBeTowed: true,
      toBeScheduled: false,
      readyToBreakIn: false,
      assignedTechnicians: [],
      temp_assignedTechnicians: [],
      lastUpdated: "",
      actualOutDate: "",
    },
  },
  {
    _id: "dummy-id-4",
    unitId: "2004",
    fms: "MiningFMS",
    modelCode: "MODEL-D",
    equipmentType: "H",
    truckType: "Utility",
    status: "operational",
    wencoStatus: null,
    minestarStatus: null,
    location: "Field",
    refreshedTime: "2025-01-04T06:00:00.000Z",
    operatingType: "Autonomous",
    activeEvent: {
      _id: "dummy-event-4",
      unitId: "2004",
      status: "operational",
      hoursInStatus: "12 hours",
      workOrderNumber: "WO-012",
      purchaseOrderNumber: "",
      scheduleOutDate: "",
      scheduledInDate: "",
      secondaryStatus: "Inspection Complete",
      location: "Field",
      bay: "",
      releasedToOps: true,
      lastUpdatedBy: "",
      updatedAt: "2025-01-04T07:00:00.000Z",
      conflict: false,
      purchaseOrderExpectedDate: "",
      isManuallyAdded: false,
      isStatusChangeManual: false,
      downDate: "2025-01-04T06:00:00.000Z",
      revisedOutDate: "",
      toBePlanned: false,
      washed: true,
      washComplete: false,
      toBeTowed: false,
      toBeScheduled: false,
      readyToBreakIn: true,
      assignedTechnicians: [],
      temp_assignedTechnicians: [],
      lastUpdated: "",
      actualOutDate: "",
    },
  },
  {
    _id: "dummy-id-5",
    unitId: "2005",
    fms: "MiningFMS",
    modelCode: "MODEL-E",
    equipmentType: "H",
    truckType: "Standard",
    status: "pending",
    wencoStatus: null,
    minestarStatus: null,
    location: "Inspection Bay",
    refreshedTime: "2025-01-05T10:00:00.000Z",
    operatingType: "Manual",
    activeEvent: {
      _id: "dummy-event-5",
      unitId: "2005",
      status: "pending",
      hoursInStatus: "16 hours",
      workOrderNumber: "WO-345",
      purchaseOrderNumber: "PO-345",
      scheduleOutDate: "",
      scheduledInDate: "",
      secondaryStatus: "Pending Inspection",
      location: "Inspection Bay",
      bay: "Bay 5",
      releasedToOps: false,
      lastUpdatedBy: "",
      updatedAt: "2025-01-05T11:00:00.000Z",
      conflict: false,
      purchaseOrderExpectedDate: "",
      isManuallyAdded: true,
      isStatusChangeManual: true,
      downDate: "2025-01-05T10:00:00.000Z",
      revisedOutDate: "",
      toBePlanned: true,
      washed: false,
      washComplete: false,
      toBeTowed: false,
      toBeScheduled: false,
      readyToBreakIn: false,
      assignedTechnicians: [],
      temp_assignedTechnicians: [],
      lastUpdated: "",
      actualOutDate: "",
    },
  },
];
